spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb;INIT=create domain if not exists xml as CLOB;MODE=MSSQLServer
jwt:
  expiration:
    time: 6000000
    